stages:
    - mavenbuild
    - maventest
    - autodeploy
    - androidbuild
    
maven-build:
    stage: mavenbuild
    tags:
        - BACKEND
    script:
        - cd BackEnd/BYTEZ_Backend
        - mvn package -B

maven-test:
    stage: maventest
    tags:
        - BACKEND
    script:
        - cd BackEnd/BYTEZ_Backend
        - mvn test
        - mvn package -B
    artifacts:
     paths:
        - BackEnd/BYTEZ_Backend/target/*.jar

autoDeploy:
    stage: autodeploy
    tags:
        - BACKEND
    script:
        - cd BackEnd/BYTEZ_Backend
        - mvn test
        - mvn package -B
        - sudo mv target/*.jar /target/web-demo.jar
        - sudo systemctl stop system-web-demo
        - sudo systemctl start system-web-demo
    only:
        refs:
            - master
        changes:
            - BackEnd/**/*
            
android-build:
	image: noahkelleher/android-ci:latest
	stage: androidbuild
	before_script:
		- export GRADLE_USER_HOME='pwd'/.gradle
		- chmod +x ./FrontEnd/BYTEZ_Frontend/gradlew
	tags:
		- FRONTEND
	script:
		- cd FrontEnd/BYTEZ_Frontend/
		- ./gradlew assemble
	artifacts:
		path:
			- FrontEnd/BYTEZ_Frontend/app/build/outputs/