stages:
    - mavenbuild
    - maventest
    - autodeploy
    
maven-build:
    stage: mavenbuild
    tags:
        - shell
    script:
        - cd Backend/BYTEZ_Backend
        - mvn package -B

maven-test:
    stage: maventest
    tags:
        -shell
    script:
        - cd Backend/BYTEZ_Backend
        - mvn test
        - mvn package -B
    artifacts:
        paths:
        - Backend/BYTEZ_Backend/target/*.jar

autoDeploy:
    stage: autodeploy
    tags:
        - shell
    script:
        - cd Backend/BYTEZ_Backend
        - mvn test
        - mvn package -B
        - sudo mv target/*.jar /target/web-demo.jar
        - sudo systemctl stop system-web-demo
        - sudo systemctl start system-web-demo